int getInt(int* input, char message[], char eMessage[], int lowLimit, int highLimit);
int getFloat(float* input, char message[], char eMessage[], float lowLimit, float highLimit);
char getChar(char* input, char message[], char eMessage[], char lowLimit, char highLimit);
char getString(char* input, char message[], char eMessage[], int lowLimit, int highLimit);
float add(float, float);
float subtract(float, float);
float divide(float, float);
float multiply(float, float);
long int factorial(float);
void pedirAlumno(int[], int[], char[], int[], int[], float[], int);
void mostrarUnAlumno(int, int, char, int, int, float);
void mostrarAlumnos(int[], int[], char[], int[], int[], float[], int);
void ordenarAlumnos(int[], int[], char[], int[], int[], float[], int);
void getNombreApellido(char[]);
